# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AnimationLottieCocoapodTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AnimationLottieCocoapodTest
pod 'lottie-ios'
pod 'SKSplashView'

  target 'AnimationLottieCocoapodTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
